apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: ansible-redis
    title: Ansible Redis Role
    description: Ansible role to manage Redis in a standalone setup or cluster.
    namespace: stone
    tags:
      - iac-library
      - ansible
    annotations:
      legacy.stone.tech/owner-email: foundation.platform@stone.com.br
spec:
    type: library
    lifecycle: production
    owner: stone-payments/tis-automation