---
#- name: enable overcommit in sysctl
#  sysctl:
#    name: vm.overcommit_memory
#    value: 1
#    state: present
#    reload: yes
#    ignoreerrors: yes
# when: redis_travis_ci is not defined

- name: install Redis {{ redis_install_ver_major }}.{{ redis_install_ver_minor }}.{{ redis_install_ver_patch }}
  package:
    name: redis-{{ redis_install_ver_major }}.{{ redis_install_ver_minor }}.{{ redis_install_ver_patch }}
    state: present
