---
- name: configure SELinux file contexts for sentinel
  sefcontext:
    target: "{{ item.target }}"
    setype: "{{ item.setype }}"
    reload: true
    state: present
  with_items:
    - target: "{{ redis_sent_sys_confFile }}"
      setype: redis_conf_t
    - target: "{{ redis_sent_sys_bin }}"
      setype: redis_exec_t
    - target: "{{ redis_sent_sys_pidFile | dirname }}(/.*)?"
      setype: redis_var_run_t

- name: ensure SELinux file context are applied to server files
  shell: restorecon -vr "{{ item }}"
  with_items:
    - "{{ redis_sent_sys_bin }}"
    - "{{ redis_sent_sys_pidFile | dirname }}"
  register: restorecon
  changed_when: restorecon.stdout != ""
  notify:
    - restart sentinel

- block:
    - name: configure SELinux file context for sentinel log folder
      sefcontext:
        target: "{{ redis_sent_log_file | dirname }}(/.*)?"
        setype: "redis_log_t"
        reload: true
        state: present

    - name: ensure SELinux file context is applied to sentinel log file
      shell: restorecon -vr "{{ redis_sent_log_file }}"
      register: restorecon_log
      changed_when: restorecon_log.stdout != ""
      notify:
        - restart sentinel
  when: redis_sent_log_file != ""

- name: create SELinux policies
  template:
    src: selinux-redis-lnkfile-init_t-redis_exec_t.te.j2
    dest: /tmp/{{ redis_sent_selinux_service_name }}.te
    owner: root
    group: root
    mode: 0644

- name: compile SELinux module
  command: checkmodule -M -m -o /tmp/{{ redis_sent_selinux_service_name }}.mod /tmp/{{ redis_sent_selinux_service_name }}.te

- name: build SELinux policy package
  command: semodule_package -o /tmp/{{ redis_sent_selinux_service_name }}.pp -m /tmp/{{ redis_sent_selinux_service_name }}.mod

- name: load SELinux module
  command: semodule -i /tmp/{{ redis_sent_selinux_service_name }}.pp

- name: configure SELinux network ports for sentinel
  seport:
    ports: "{{ redis_sent_conn_port }}"
    proto: tcp
    setype: redis_port_t
    reload: true
    state: present
  notify:
    - restart sentinel
