---
- name: create redis config file
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    mode: 0640
  notify: restart redis

# Flush handlers before ensuring the service is started to prevent
# a start and then restart
- name: flush handlers to apply config changes
  meta: flush_handlers

- name: ensure redis is running and enabled
  service:
    name: redis
    state: started
    enabled: true
