---
- name: configure SELinux file contexts for server
  sefcontext:
    target: "{{ item.target }}"
    setype: "{{ item.setype }}"
    reload: true
    state: present
  with_items:
    - target: "{{ redis_srv_sys_confFile }}"
      setype: redis_conf_t
    - target: "{{ redis_srv_sys_bin }}"
      setype: redis_exec_t
    - target: "{{ redis_srv_stor_dir }}(/.*)?"
      setype: redis_var_lib_t
    - target: "{{ redis_srv_sys_pidFile | dirname }}(/.*)?"
      setype: redis_var_run_t

- name: ensure SELinux file context are applied to server files
  shell: restorecon -vr "{{ item }}"
  with_items:
    - "{{ redis_srv_sys_bin }}"
    - "{{ redis_srv_stor_dir }}"
    - "{{ redis_srv_sys_pidFile | dirname }}"
  register: restorecon
  changed_when: restorecon.stdout != ""
  notify:
    - restart redis

- block:
    - name: configure SELinux file context for server log folder
      sefcontext:
        target: "{{ redis_srv_log_file | dirname }}(/.*)?"
        setype: "redis_log_t"
        reload: true
        state: present

    - name: ensure SELinux file context is applied to server log file
      shell: restorecon -vr "{{ redis_srv_log_file }}"
      register: restorecon_log
      changed_when: restorecon_log.stdout != ""
      notify:
        - restart redis
  when: redis_srv_log_file != ""

- name: configure SELinux network ports for server
  seport:
    ports: "{{ redis_srv_conn_port }}"
    proto: tcp
    setype: redis_port_t
    reload: true
    state: present
  notify:
    - restart redis
