---
- name: enable overcommit in sysctl
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes
    ignoreerrors: true

- name: configure server-writable folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ redis_srv_sys_user }}"
    group: "{{ redis_srv_sys_group }}"
    mode: "0755"
  with_items:
    - "{{ redis_srv_stor_dir }}"
    - "{{ redis_srv_sys_pidFile | dirname }}"

- name: configure server-writable filepaths
  file:
    path: "{{ item }}"
    state: file
    owner: "{{ redis_srv_sys_user }}"
    group: "{{ redis_srv_sys_group }}"
    mode: "0644"
  with_items:
    - "{{ redis_srv_stor_dir }}/{{ redis_srv_stor_dbFile }}"
    - "{{ redis_srv_stor_dir }}/{{ redis_srv_stor_appendFile }}"
    - "{{ redis_srv_sys_pidFile }}"
  failed_when: false

- block:
  - name: configure server log folder
    file:
      path: "{{ redis_srv_log_file | dirname }}"
      state: directory
      owner: "{{ redis_srv_sys_user }}"
      group: "{{ redis_srv_sys_group }}"
      mode: "0755"

  - name: configure server log filepath
    file:
      path: "{{ redis_srv_log_file }}"
      state: file
      owner: "{{ redis_srv_sys_user }}"
      group: "{{ redis_srv_sys_group }}"
      mode: "0644"
  when: redis_srv_log_file != ""

- name: create redis config file
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    mode: "0600"
  notify: restart redis

- name: install server service file
  template:
    src: "redis.service.j2"
    dest: "/etc/systemd/system/redis.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload systemd
    - restart redis

- name: configure SELinux for server
  include: server_selinux.yml
  when: ansible_selinux

# Flush handlers before ensuring the service is started to prevent
# a start and then restart
- name: flush handlers to apply config changes
  meta: flush_handlers

- name: ensure redis is running and enabled
  service:
    name: redis
    state: started
    enabled: true
