---
- name: reload systemd
  shell: systemctl daemon-reload

- name: restart redis
  service:
    name: redis
    state: restarted

- name: restart sentinel
  service:
    name: redis-sentinel
    state: restarted
