---
- name: "Restart redis"
  service:
    name: "{{ redis_service_name }}"
    state: restarted

- name: "Restart newrelic-infra"
  service:
    name: "newrelic-infra"
    state: restarted

- name: "Reload systemd"
  systemd:
    daemon_reload: yes

- name: "Make Test Redis"
  shell: make test
  args:
    chdir: /usr/local/src/redis-{{ redis_version }}

- name: "Rebuild grub"
  command:
    cmd: /sbin/grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when:
    - redis_reboot_allowed is defined
    - redis_reboot_allowed | bool